/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as SearchTestRouteImport } from './routes/search-test'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ModelTestRouteImport } from './routes/model-test'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ExecutionsRouteImport } from './routes/executions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as ResearchHistoryRouteImport } from './routes/research.history'
import { Route as ResearchReportIdRouteImport } from './routes/research.$reportId'
import { Route as MemorySemanticRouteImport } from './routes/memory.semantic'
import { Route as MemoryEpisodesRouteImport } from './routes/memory.episodes'
import { Route as MemoryMemoryIdRouteImport } from './routes/memory.$memoryId'
import { Route as ExecutionsExecutionIdRouteImport } from './routes/executions.$executionId'
import { Route as WorkspacesWorkspaceIdResearchRouteImport } from './routes/workspaces.$workspaceId.research'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchTestRoute = SearchTestRouteImport.update({
  id: '/search-test',
  path: '/search-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelTestRoute = ModelTestRouteImport.update({
  id: '/model-test',
  path: '/model-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsRoute = ExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WorkspacesRoute,
} as any)
const ResearchHistoryRoute = ResearchHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchReportIdRoute = ResearchReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => ResearchRoute,
} as any)
const MemorySemanticRoute = MemorySemanticRouteImport.update({
  id: '/semantic',
  path: '/semantic',
  getParentRoute: () => MemoryRoute,
} as any)
const MemoryEpisodesRoute = MemoryEpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => MemoryRoute,
} as any)
const MemoryMemoryIdRoute = MemoryMemoryIdRouteImport.update({
  id: '/$memoryId',
  path: '/$memoryId',
  getParentRoute: () => MemoryRoute,
} as any)
const ExecutionsExecutionIdRoute = ExecutionsExecutionIdRouteImport.update({
  id: '/$executionId',
  path: '/$executionId',
  getParentRoute: () => ExecutionsRoute,
} as any)
const WorkspacesWorkspaceIdResearchRoute =
  WorkspacesWorkspaceIdResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/executions': typeof ExecutionsRouteWithChildren
  '/memory': typeof MemoryRouteWithChildren
  '/model-test': typeof ModelTestRoute
  '/research': typeof ResearchRouteWithChildren
  '/search-test': typeof SearchTestRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
  '/memory/$memoryId': typeof MemoryMemoryIdRoute
  '/memory/episodes': typeof MemoryEpisodesRoute
  '/memory/semantic': typeof MemorySemanticRoute
  '/research/$reportId': typeof ResearchReportIdRoute
  '/research/history': typeof ResearchHistoryRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/research': typeof WorkspacesWorkspaceIdResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/executions': typeof ExecutionsRouteWithChildren
  '/memory': typeof MemoryRouteWithChildren
  '/model-test': typeof ModelTestRoute
  '/research': typeof ResearchRouteWithChildren
  '/search-test': typeof SearchTestRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
  '/memory/$memoryId': typeof MemoryMemoryIdRoute
  '/memory/episodes': typeof MemoryEpisodesRoute
  '/memory/semantic': typeof MemorySemanticRoute
  '/research/$reportId': typeof ResearchReportIdRoute
  '/research/history': typeof ResearchHistoryRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/research': typeof WorkspacesWorkspaceIdResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/executions': typeof ExecutionsRouteWithChildren
  '/memory': typeof MemoryRouteWithChildren
  '/model-test': typeof ModelTestRoute
  '/research': typeof ResearchRouteWithChildren
  '/search-test': typeof SearchTestRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
  '/memory/$memoryId': typeof MemoryMemoryIdRoute
  '/memory/episodes': typeof MemoryEpisodesRoute
  '/memory/semantic': typeof MemorySemanticRoute
  '/research/$reportId': typeof ResearchReportIdRoute
  '/research/history': typeof ResearchHistoryRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/research': typeof WorkspacesWorkspaceIdResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/executions'
    | '/memory'
    | '/model-test'
    | '/research'
    | '/search-test'
    | '/workspaces'
    | '/executions/$executionId'
    | '/memory/$memoryId'
    | '/memory/episodes'
    | '/memory/semantic'
    | '/research/$reportId'
    | '/research/history'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/executions'
    | '/memory'
    | '/model-test'
    | '/research'
    | '/search-test'
    | '/workspaces'
    | '/executions/$executionId'
    | '/memory/$memoryId'
    | '/memory/episodes'
    | '/memory/semantic'
    | '/research/$reportId'
    | '/research/history'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/research'
  id:
    | '__root__'
    | '/'
    | '/executions'
    | '/memory'
    | '/model-test'
    | '/research'
    | '/search-test'
    | '/workspaces'
    | '/executions/$executionId'
    | '/memory/$memoryId'
    | '/memory/episodes'
    | '/memory/semantic'
    | '/research/$reportId'
    | '/research/history'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExecutionsRoute: typeof ExecutionsRouteWithChildren
  MemoryRoute: typeof MemoryRouteWithChildren
  ModelTestRoute: typeof ModelTestRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  SearchTestRoute: typeof SearchTestRoute
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-test': {
      id: '/search-test'
      path: '/search-test'
      fullPath: '/search-test'
      preLoaderRoute: typeof SearchTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-test': {
      id: '/model-test'
      path: '/model-test'
      fullPath: '/model-test'
      preLoaderRoute: typeof ModelTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions': {
      id: '/executions'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof ExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/research/history': {
      id: '/research/history'
      path: '/history'
      fullPath: '/research/history'
      preLoaderRoute: typeof ResearchHistoryRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/$reportId': {
      id: '/research/$reportId'
      path: '/$reportId'
      fullPath: '/research/$reportId'
      preLoaderRoute: typeof ResearchReportIdRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/memory/semantic': {
      id: '/memory/semantic'
      path: '/semantic'
      fullPath: '/memory/semantic'
      preLoaderRoute: typeof MemorySemanticRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/memory/episodes': {
      id: '/memory/episodes'
      path: '/episodes'
      fullPath: '/memory/episodes'
      preLoaderRoute: typeof MemoryEpisodesRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/memory/$memoryId': {
      id: '/memory/$memoryId'
      path: '/$memoryId'
      fullPath: '/memory/$memoryId'
      preLoaderRoute: typeof MemoryMemoryIdRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/executions/$executionId': {
      id: '/executions/$executionId'
      path: '/$executionId'
      fullPath: '/executions/$executionId'
      preLoaderRoute: typeof ExecutionsExecutionIdRouteImport
      parentRoute: typeof ExecutionsRoute
    }
    '/workspaces/$workspaceId/research': {
      id: '/workspaces/$workspaceId/research'
      path: '/research'
      fullPath: '/workspaces/$workspaceId/research'
      preLoaderRoute: typeof WorkspacesWorkspaceIdResearchRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
  }
}

interface ExecutionsRouteChildren {
  ExecutionsExecutionIdRoute: typeof ExecutionsExecutionIdRoute
}

const ExecutionsRouteChildren: ExecutionsRouteChildren = {
  ExecutionsExecutionIdRoute: ExecutionsExecutionIdRoute,
}

const ExecutionsRouteWithChildren = ExecutionsRoute._addFileChildren(
  ExecutionsRouteChildren,
)

interface MemoryRouteChildren {
  MemoryMemoryIdRoute: typeof MemoryMemoryIdRoute
  MemoryEpisodesRoute: typeof MemoryEpisodesRoute
  MemorySemanticRoute: typeof MemorySemanticRoute
}

const MemoryRouteChildren: MemoryRouteChildren = {
  MemoryMemoryIdRoute: MemoryMemoryIdRoute,
  MemoryEpisodesRoute: MemoryEpisodesRoute,
  MemorySemanticRoute: MemorySemanticRoute,
}

const MemoryRouteWithChildren =
  MemoryRoute._addFileChildren(MemoryRouteChildren)

interface ResearchRouteChildren {
  ResearchReportIdRoute: typeof ResearchReportIdRoute
  ResearchHistoryRoute: typeof ResearchHistoryRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchReportIdRoute: ResearchReportIdRoute,
  ResearchHistoryRoute: ResearchHistoryRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

interface WorkspacesWorkspaceIdRouteChildren {
  WorkspacesWorkspaceIdResearchRoute: typeof WorkspacesWorkspaceIdResearchRoute
}

const WorkspacesWorkspaceIdRouteChildren: WorkspacesWorkspaceIdRouteChildren = {
  WorkspacesWorkspaceIdResearchRoute: WorkspacesWorkspaceIdResearchRoute,
}

const WorkspacesWorkspaceIdRouteWithChildren =
  WorkspacesWorkspaceIdRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteChildren,
  )

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRouteWithChildren
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRouteWithChildren,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExecutionsRoute: ExecutionsRouteWithChildren,
  MemoryRoute: MemoryRouteWithChildren,
  ModelTestRoute: ModelTestRoute,
  ResearchRoute: ResearchRouteWithChildren,
  SearchTestRoute: SearchTestRoute,
  WorkspacesRoute: WorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
