/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExecutionsExecutionIdRouteImport } from './routes/executions.$executionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsExecutionIdRoute = ExecutionsExecutionIdRouteImport.update({
  id: '/executions/$executionId',
  path: '/executions/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/executions/$executionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/executions/$executionId'
  id: '__root__' | '/' | '/executions/$executionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExecutionsExecutionIdRoute: typeof ExecutionsExecutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/$executionId': {
      id: '/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/executions/$executionId'
      preLoaderRoute: typeof ExecutionsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExecutionsExecutionIdRoute: ExecutionsExecutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
